global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Redis Streams MQ service
  - job_name: 'redis-streams-mq'
    static_configs:
      - targets: ['host.docker.internal:8083']  # Health server port
    metrics_path: '/metrics/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis server metrics (if redis_exporter is available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
