redis:
  host: ${REDIS_HOST:-localhost}
  port: ${REDIS_PORT:-6379}
  password: ${REDIS_PASSWORD:-}
  database: ${REDIS_DATABASE:-0}
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  retry_backoff: 8ms
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 5m
  client_name: example-app

streams:
  default_max_len: 100000
  default_max_age: 24h
  default_trim_strategy: "MAXLEN"
  auto_create_streams: true
  trim_interval: 5m

consumers:
  default_batch_size: 10
  default_block_timeout: 100ms
  default_consumer_timeout: 5s
  default_auto_ack: true
  max_pending_messages: 5000
  claim_min_idle_time: 10s
  claim_interval: 15s

topics:
  - name: "example.topic"
    stream_name: "example:topic"
    max_len: 50000
    max_age: 24h
    trim_strategy: "MAXLEN"
    consumer_group: "example-group"
    retry_attempts: 3
    description: "Example topic"

monitoring:
  enabled: true
  metrics_interval: 5s
  health_check_port: 8083
  prometheus_path: "/metrics"

logging:
  level: ${LOG_LEVEL:-INFO}
  format: ${LOG_FORMAT:-json}
  output: ${LOG_OUTPUT:-stdout}
  structured: true


