redis:
  host: 0.0.0.0
  port: 6379
  password: Neeraj123
  database: 2
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  retry_backoff: 8ms
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 5m
  client_name: example-app

streams:
  default_max_len: 100000
  default_max_age: 24h
  default_trim_strategy: "MAXLEN"
  auto_create_streams: true
  trim_interval: 5m

consumers:
  default_batch_size: 10
  default_block_timeout: 100ms
  default_consumer_timeout: 5s
  default_auto_ack: true
  delete_after_ack: true
  max_pending_messages: 5000
  claim_min_idle_time: 10s
  claim_interval: 15s

topics:
  - name: "user.lookup"
    stream_name: "user:lookup"
    max_len: 100000
    max_age: 24h
    trim_strategy: "MAXLEN"
    consumer_group: "user-lookup-group"
    retry_attempts: 3
    description: "User lookup events"

  - name: "user.failed.lookup"
    stream_name: "user:failed.lookup"
    max_len: 100000
    max_age: 24h
    trim_strategy: "MAXLEN"
    consumer_group: "user-lookup-group"
    retry_attempts: 3
    description: "User lookup failed events"

monitoring:
  enabled: true
  metrics_interval: 5s
  health_check_port: 8083
  prometheus_path: "/metrics"

logging:
  level: "INFO"
  format: "json"
  output: "stdout"
  structured: true